<div class="container-fluid">
	<div class="page-title">
		<div class="row">
			<div class="col s12 m9 l10">
				<h1>Layout Salic</h1>

				<ul id="migalhas">
					<li><a  href="#"><i class="material-icons">home</i>Home</a> /</li>
					<li>
						<a href="#">Category</a> /
					</li>
					<li><a href="widgets.html">Widgets</a></li>
				</ul>
			</div>
			<div class="col s12 m3 l2 right-align">
				<a href="javascript:voltar();" title="Página Anterior"title="Página Anterior" class="btn small grey lighten-3 grey-text z-depth-0 chat-toggle"><i class="material-icons">keyboard_return</i>
				</a>
			</div>
		</div>
	</div>

	<div class="content">
		<p>
			Esse é o esqueleto de uma página simples, sem menu.
			Caso a página contenha textos fora de tabelas, crie uma <strong>div</strong>
			com o atributo <strong>id="miolo"</strong> e coloque o conteúdo dentro da mesma.
			Caso precise utilizar a margem mais de uma vez na mesma página, utilize o atributo <strong>class="miolo"</strong>.
			Esse é um exemplo de texto que está fora de <strong>&lt;div id="miolo"&gt; &lt;/div&gt;</strong>.
		</p>
		<br />

		<table class="tabela">
			<tr>
				<th>Esqueleto de Página Simples</th>
			</tr>
			<tr>
				<td>Esse é o esqueleto de uma página simples, sem menu.</td>
			</tr>
		</table>
	</div>
</div>